name: SFDX Test Run on Push

on: [push]


jobs:
    deploy_to_sandbox:

        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            uses: actions/checkout@master
            with:
               ref: ${{ github.ref }}

          - uses: sfdx-actions/setup-sfdx@v1
            with:
              sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
          - name: sfdx-test-run
            run: sfdx force:source:deploy --sourcepath force-app/main/default --json --loglevel fatal
          - name: sfdx-test-run
            run: sfdx force:apex:test:run -l RunLocalTests -w 30