name: SFDX Test Run on Push

on: [push]


jobs:
    push_to_sf:

        runs-on: ubuntu-latest

        steps:
          - name: checkout current branch
            uses: actions/checkout@master
            with:
               ref: ${{ github.ref }}
          - uses: sfdx-actions/setup-sfdx@v1
            with:
              sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
          - name: push branch to authorized salesforce org
            run: sfdx force:source:deploy --sourcepath force-app/main/default --json --loglevel fatal
          - name: run local tests on salesforce org
            run: sfdx force:apex:test:run -l RunLocalTests -w 30         
